---
- hosts: seedboxes
  vars:
    http_port: 80
    scgi_port: 5000
  remote_user: root
  roles:
  - firewall
  - ssh

  hosts: seedboxes
  roles:
  - ssl
  - { role: apache, when: apache == true }
  - { role: nginx, when: nginx == true }
  - php

  hosts: seedboxes
  roles:
  - rtorrent
  - rutorrent
  - { role: ruplugins, when: ruplugins == true }

  hosts: seedboxes
  roles:
  - sickrage

  host: seedboxes
  roles:
  - couchpotato
