---
- name: Install rtorrent Dependancies
  apt: pkg={{ item }} state=present
  with_items:
  - libcurl3
  - ncurses-base
  - subversion

- name: Make sources directory
  file: path=~/sources state=directory

- name: Get and Make xmlrpc
  command: chdir=~/sources/ "svn co https://xmlrpc-c.svn.sourceforge.net/svnroot/xmlrpc-c/stable xmlrpc"
  command: chdir=~/sources/xmlrpc "{{ item }}"
  with_items:
  - ./configure --prefix=/usr --enable-libxml2-backend --disable-libwww-client --disable-wininet-client --disable-abyss-server --disable-cgi-server
  - make
  - make install

- name: Get libtorrent
#  get_url: url=http://libtorrent.rakshasa.no/downloads/libtorrent-0.13.4.tar.gz dest=~/sources
  unarchive: src=http://libtorrent.rakshasa.no/downloads/libtorrent-0.13.4.tar.gz
             dest=~/sources
#  command: chdir=~/sources/ "tar -xzf libtorrent-0.13.4.tar.gz"

- name: Make libtorrent
  command: chdir=~/sources/libtorrent-0.13.4 "{{ item }}"
  with_items:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j2
  - make install

- name: Get rtorrent
#  get_url: url=http://libtorrent.rakshasa.no/downloads/rtorrent-0.9.4.tar.gz dest=~/sources
  unarchive: src=http://libtorrent.rakshasa.no/downloads/rtorrent-0.9.4.tar.gz
             dest=~/sources
#  command: chdir=~/sources/ "tar -xzf rtorrent-0.9.4.tar.gz"

- name: Make rtorrent
  command: chdir=~/sources/rtorrent-0.9.4/ "{{ item }}" 
  with_items:
  - ./autogen.sh
  - .configure --prefix=/usr --with-xmlrpc-c
  - make -j2
  - make install
  - ldconfig
