---
- name: Install rtorrent Dependancies
  apt: pkg={{ item }} state=present
  with_items:
  - libcurl3-dev
  - ncurses-base
  - subversion

- name: Make sources directory
  file: path=/home/{{ ansible_env.SUDO_USER }}/sources
        state=directory

- name: Get xmlrpc
  shell: 'cd /home/{{ ansible_env.SUDO_USER }}/sources; svn co https://xmlrpc-c.svn.sourceforge.net/svnroot/xmlrpc-c/stable xmlrpc'

- name: Make xmlrpc
  shell: 'cd /home/{{ ansible_env.SUDO_USER }}/sources/xmlrpc; {{ item }}'
  with_items:
  - ./configure --prefix=/usr --enable-libxml2-backend --disable-libwww-client --disable-wininet-client --disable-abyss-server --disable-cgi-server
  - make
  - make install

- name: Get libtorrent
  unarchive: src=libtorrent-0.13.6.tar.gz
             dest=/home/{{ ansible_env.SUDO_USER }}/sources

- name: Make libtorrent
  shell: 'cd /home/{{ ansible_env.SUDO_USER }}/sources/libtorrent-0.13.6; {{ item }}'
  with_items:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j2
  - make install

- name: Get rtorrent
  unarchive: src=rtorrent-0.9.6.tar.gz
             dest=/home/{{ ansible_env.SUDO_USER }}/sources

- name: Make rtorrent
  shell: 'cd /home/{{ ansible_env.SUDO_USER }}/sources/rtorrent-0.9.6; {{ item }}'
  with_items:
  - ./autogen.sh
  - ./configure --prefix=/usr --with-xmlrpc-c
  - make -j2
  - make install
  - ldconfig

- name: Configure rtorrent
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: 'rtorrent.j2', dest: "/home/{{ torrent_user }}/.rtorrent.rc" }
  - { src: 'rtorrent.conf.j2', dest: '/etc/init/rtorrent.conf' }

- name: Create rtorrent directories
  file: path=/home/{{ torrent_user }}/{{ item }} state=directory
  with_items:
  - downloads
  - downloads/watch
  - downloads/.session
