---
- name: Install rutorrent Dependancies
  apt: pkg={{ item }} state=present
  with_items:
  - git
  - unzip
  - unrar-free

- name: Template rutorrent virtual host
  template: src=default-site.j2 dest=/etc/apache2/sites-available/default

- name: Clone ruTorrent git
  git: repo=https://github.com/Novik/ruTorrent.git dest=/var/www/ruTorrent
  when: git == true

- name: Set ownership of ruTorrent
  file: path=/var/www/ruTorrent recurse=yes owner=www-data group=www-data mode=755

- name: Configure ruTorrent
  template: src=config.php.j2 dest=/var/www/ruTorrent/conf/config.php

- name: Configure ruTorrent Plugins
  template: src=plugins.ini.j2 dest=/var/www/ruTorrent/conf/plugins.ini
