---
- name: Install PHP5
  apt: pkg=php5 state=present

- name: Install PHP5 Extras
  apt: pkg={{ item }} state=present
  with_items:
  - php5
  - php5-cli
  - php5-dev
  - php5-fpm
  - php5-curl
  - php5-geoip
  - php5-mcrypt
  - php5-xmlrpc
  notify: apache restart
